name: EmauAPI
version: '${project.version}'
main: fr.maxairfrance.azplugin.bukkit.EmauAPI
author: MaxAirFrance
depend: [ProtocolLib]
commands:
  az:
    description: commande du plugin.
    permission: emauapi.commands
    permission-message: §cVous n'avez pas la permission d'utiliser cette commande !

permissions:
  emauapi.*:
    description: Permet de mettre toutes les permission
    default: op
  emauapi.command.size:
    description: Permission pour la commande principale
    default: op
  emauapi.command.check:
    description: Permission pour la sous-commande 1
    default: op
  emauapi.command.list:
    description: Permission pour la sous-commande 1
    default: op
  emauapi.command.itemrender:
    description: Permission pour la sous-commande 1
    default: op
  emauapi.command.opacity:
    description: Permission pour la sous-commande 1
    default: op
  emauapi.command.worldenv:
    description: Permission pour la sous-commande 1
    default: op

